### PR TITLE
feat: add markdownlint

### LINKED ISSUE #60: Add markdownlint to gulp task lint
Please, add a `markdownlint` to gulp task `lint`. 

Reccomendadtion: 
- [markdownlint](https://github.com/DavidAnson/markdownlint#usage)

### PR DESCRIPTION
**Pull request by romanrostislavovich**
Added markdownlint to the project.

added next gulp commands:
- `lint-markdown` - check all `.md` files via `markdownlint`

Closes #60

### CODE REVIEW

**Review by xferra — CHANGES_REQUESTED** [review]
I hope this is `ci` PR?

**Comment by xferra** [comment]
I'm not sure, but could we avoid an extra dep `thoght2`?

**Comment by romanrostislavovich** [comment]
@xferra Yes, this is `ci` PR, my mistake and I fix it, sorry. The package `thoughty2` is the recommendation to used with `gulp` at developers `markdownlint`. But I can try to refactor it without this package.

**Comment by romanrostislavovich** [comment]
Branch name don't valid. New PR #68

**Pull request closed without merging**
