### PR TITLE
feat: restrict additional properties in core schemas

### LINKED ISSUE #82: Core schemas should be sealed
Any extra properties in core schemas should be forbidden at the root level. It at least will show that some tests are broken 👿

### PR DESCRIPTION
**Pull request by romanrostislavovich**
added sealed for core schemas

Closes #82

### CODE REVIEW

**Comment by xferra** [comment]
Let's move it the next release. I don't see how schemas are closed e.g. sealed; basically, it means there is no possibility to extend internal definitions it in any way.

**Review by xferra — CHANGES_REQUESTED** [review]
Not done

**Comment by xferra** [comment]
@svoboda-rabstvo please review all schemas and restrict extra props where possible (for example `deps` file should not have any additional properties at the root level and nested definitions - it means that schema should fail in case of extra properties).

**Comment by romanrostislavovich** [comment]
@xferra  I suggest closes all `sub prop` for now. Because in `json-schema-org` don't have a correct answer to how to use `additionalProperties: false` with `allOf` in root level. In the future, they will find a single solution (possiblein it's in draft-07 or draft-08)

**Comment by xferra** [comment]
Please add a link to the thread, just for history.

**Review by xferra — APPROVED** [review]
+1

**Pull request merged**
