### PR TITLE
test: Add new tests which check the $version and $schema properties

### LINKED ISSUE #103: Add new tests for $version and $schema properties
Please, add new tests for `$version` and `$schema` properties in core schemas

Related #95

### PR DESCRIPTION
**Pull request by romanrostislavovich**
Added tests for core schemas, which check `$version` and `$schema` properties

Closes #103

### CODE REVIEW

**Review by xferra — APPROVED** [review]
I don't think that several tests above give us any value, coz from OOP point of view we should have a 1 test for base object, and not n tests for inherited which validate a property from base type definition.

**Comment by romanrostislavovich** [comment]
There's no such thing as so much tests, especial for ~~(us)~~ me. You know about I saying ;)

**Comment by xferra** [comment]
@svoboda-rabstvo still to avoid unnecessary updates and extra efforts to support duplicates ([test/deps/files/schema.example.absent.json](), [test/linter/files/schema.example.absent.json]()) we need to remove it someday.

**Comment by xferra** [comment]
BTW it a new type of issue wowow 🎉`technical debt`, hello **techdebt**, you're welcome! 🤣

**Pull request merged**
