### PR TITLE
feat: add new properties $version and $schema to core schemas

### LINKED ISSUE #95: New properties in core schemas
Please, add following properties to `deps`, `package` and `linter` schemas:
- `$version` - describe a version of the schema
- `$schema` - used to declare that a JSON fragment is actually a piece of JSON Schema

### PR DESCRIPTION
**Pull request by romanrostislavovich**
Added new properties `$version` and `$schema` to core schemas

Closes #95

### CODE REVIEW

**Comment by xferra** [comment]
Incorrect, the only thing that I could suggest - please review JSON Schema spec or examples how to extend it. The `$schema` definition is completely incorrect.

**Comment by svoboda-rabstvo** [comment]
We need a common style of schemas format

**Comment by svoboda-rabstvo** [comment]
If I understand correctly property `$schema` must not appear in subschemas and set only in root `schema`. For that matter we can't set it a require property

**Review by xferra — APPROVED** [review]
+1
The only thing I could suggest - using `self` of `concrete_name_like_package` for object definitions.

**Pull request merged**
