### PR TITLE
test: add test for test core schema

### LINKED ISSUE #106: Validate test cases
Please, add validate schema of test cases

Related #92

### PR DESCRIPTION
**Pull request by romanrostislavovich**
added tests for `test.json` schema

Closes #106

### CODE REVIEW

**Comment by xferra** [comment]
This is not a core schema, hope it's clear; So, lets move out it from other core schemas together with imports. After that please review tests that you've added, some of them seems to be useless.

**Review by xferra — CHANGES_REQUESTED** [review]
Tests and import schema should be moved out from schema folder.

**Comment by romanrostislavovich** [comment]
I create separate issues for moved out that schemas from `schema` folder

**Comment by xferra** [comment]
Please read carefully my remarks above. The issue is not only in schemas, some tests are useless.

**Comment by romanrostislavovich** [comment]
I removed useless tests

**Review by xferra — APPROVED** [review]
+1

**Pull request merged**
